# coding: utf-8

"""
    Heladería Via Apilia

    API de la Heladería Via Apilia. A través de esta API se pueden consultar los gustos de helado y realizar pedidos.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: devs@heladeria-apilia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.datos_de_pago import DatosDePago  # noqa: F401,E501

class DatosDePagoBilleteraVirtual(DatosDePago):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str'
    }
    if hasattr(DatosDePago, "swagger_types"):
        swagger_types.update(DatosDePago.swagger_types)

    attribute_map = {
        'alias': 'alias'
    }
    if hasattr(DatosDePago, "attribute_map"):
        attribute_map.update(DatosDePago.attribute_map)

    def __init__(self, alias=None, *args, **kwargs):  # noqa: E501
        """DatosDePagoBilleteraVirtual - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self.discriminator = None
        self.alias = alias
        DatosDePago.__init__(self, *args, **kwargs)

    @property
    def alias(self):
        """Gets the alias of this DatosDePagoBilleteraVirtual.  # noqa: E501

        nombre de usuario o alias de la billetera a utilizar  # noqa: E501

        :return: The alias of this DatosDePagoBilleteraVirtual.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this DatosDePagoBilleteraVirtual.

        nombre de usuario o alias de la billetera a utilizar  # noqa: E501

        :param alias: The alias of this DatosDePagoBilleteraVirtual.  # noqa: E501
        :type: str
        """
        if alias is None:
            raise ValueError("Invalid value for `alias`, must not be `None`")  # noqa: E501

        self._alias = alias

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatosDePagoBilleteraVirtual, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatosDePagoBilleteraVirtual):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
