# coding: utf-8

"""
    Heladería Via Apilia

    API de la Heladería Via Apilia. A través de esta API se pueden consultar los gustos de helado y realizar pedidos.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: devs@heladeria-apilia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Pedido(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'direccion_entrega': 'str',
        'links': 'PedidoLinks'
    }

    attribute_map = {
        'id': 'id',
        'direccion_entrega': 'direccion_entrega',
        'links': '_links'
    }

    def __init__(self, id=None, direccion_entrega=None, links=None):  # noqa: E501
        """Pedido - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._direccion_entrega = None
        self._links = None
        self.discriminator = None
        self.id = id
        self.direccion_entrega = direccion_entrega
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this Pedido.  # noqa: E501

        identificador de este pedido  # noqa: E501

        :return: The id of this Pedido.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Pedido.

        identificador de este pedido  # noqa: E501

        :param id: The id of this Pedido.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def direccion_entrega(self):
        """Gets the direccion_entrega of this Pedido.  # noqa: E501

        dirección en la que se ha de entregar este pedido  # noqa: E501

        :return: The direccion_entrega of this Pedido.  # noqa: E501
        :rtype: str
        """
        return self._direccion_entrega

    @direccion_entrega.setter
    def direccion_entrega(self, direccion_entrega):
        """Sets the direccion_entrega of this Pedido.

        dirección en la que se ha de entregar este pedido  # noqa: E501

        :param direccion_entrega: The direccion_entrega of this Pedido.  # noqa: E501
        :type: str
        """
        if direccion_entrega is None:
            raise ValueError("Invalid value for `direccion_entrega`, must not be `None`")  # noqa: E501

        self._direccion_entrega = direccion_entrega

    @property
    def links(self):
        """Gets the links of this Pedido.  # noqa: E501


        :return: The links of this Pedido.  # noqa: E501
        :rtype: PedidoLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Pedido.


        :param links: The links of this Pedido.  # noqa: E501
        :type: PedidoLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pedido, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pedido):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
